# auto-labeler "full" schema

# enable auto-labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'bug':
    include:
      - '\bbug[s]?\b'
    exclude: []
  'help wanted':
    include:
      - '\bhelp( me)?\b'
    exclude:
      - '\b\[test(ing)?\]\b'
  'enhancement':
    include:
      - '\bfeat\b'
      - '\bfeature\b'
    exclude: []
  'docs':
    include:
      - '\bdocs
    exclude: []
  'manager':
    include:
      - '\b(?i)manager\b'
    exclude: []
  'sdk':
    include:
      - '\b(?i)sdk\b'
    exclude: []
  'rootcause':
    include:
      - '\b(?i)rootcause\b'
    exclude: []
  'runtime':
    include:
      - '\b(?i)runtime\b'
    exclude: []
  'protos':
    include:
      - '\b(?i)protos\b'
    exclude: []
  'sonar':
    include:
      - '\b(?i)sonar\b'
    exclude: []
  'autood':
    include:
      - '\b(?i)autood\b'
    exclude: []
  'gateway':
    include:
      - '\b(?i)gateway\b'
    exclude: []
  'visualization':
    include:
      - '\b(?i)visualization\b'
    exclude: []
