lazy val codegen = project.in(file("codegen"))

lazy val manager = project.in(file("."))
  .dependsOn(codegen)
  .configs(IntegrationTest)
  .settings(Defaults.itSettings)
  .settings(Settings.all)
  .settings(SlickGen.settings)
  .settings(ManagerDev.settings)
  .settings(libraryDependencies ++= Dependencies.hydroServingManagerDependencies)
