name: 'Update & Merge Compose File'
description: 'update contents of the repo for testing compose file'
inputs:
  registry_url:
    description: dockerhub registry url
    required: true

  service_image_name:
    description: the name of the image to be updated
    required: true
        
  tag:
    description: version tag of the image
    required: true

runs:
  using: "composite"

  steps:
    - name: Set dynamic environment variables
      id: var
      shell: bash
      run: |
        case ${{ inputs.service_image_name }} in

          serving-gateway)
            SERVICE_NAME=hydro-serving-gateway
            ;;

          serving-manager)
            SERVICE_NAME=hydro-serving-manager
            ;;

          hydro-root-cause)
            SERVICE_NAME=hydro-root-cause
            ;;

          sonar)
            SERVICE_NAME=sonar
            ;;

          hydro-stat)
            SERVICE_NAME=hydro-stat
            ;;

          hydro-serving-ui)
            SERVICE_NAME=hydro-serving-ui
            ;;  

          hydro-auto-od)
            SERVICE_NAME=hydro-auto-od
            ;;  

          hydro-visualization)
            SERVICE_NAME=hydro-visualization
            ;;

          *)
            echo "unknown IMAGE_NAME"
            exit 1
            ;;
        esac

        echo ::set-output name=SERVICE_NAME::$SERVICE_NAME
      
      # TODO: linting and stuff

    - name: Update docker-compose service image
      run: "cd docker-compose && sed -i \"s/.*image:.*/    image: ${{ inputs.registry_url }}\\/${{ inputs.service_image_name }}:${{ inputs.tag }}/g\" ${{ steps.var.outputs.SERVICE_NAME }}.service.template"
      shell: bash
      
    - name: Merge compose file
      shell: bash
      run: |
        cd docker-compose
        command="docker-compose"
        for template in $(ls *.template)
        do
          command="$command -f $template"
        done

        command="$command config"
        $command > ../docker-compose.yaml  
