apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "serving.name" . }}
    chart: {{ include "serving.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  awsAccessKeyID: {{ .Values.global.persistence.accessKey | b64enc | quote }}
  awsSecretAccessKey: {{ .Values.global.persistence.secretKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "serving.name" . }}
    chart: {{ include "serving.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.global.mongodb.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "serving.name" . }}
    chart: {{ include "serving.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.global.postgresql.password | b64enc | quote }}
---
{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-docker-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "serving.name" . }}
    chart: {{ include "serving.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "serving.dockerconfig" . }}
{{- end }}
