{{- if and .Values.global.persistence.mode (eq .Values.global.persistence.mode "minio")}}
{{- if (include "minio.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ if .Values.global.persistence.accessKey }}{{ .Values.global.persistence.accessKey | b64enc | quote }}{{ else }}{{ include "minio.accessKey" . | b64enc | quote }}{{ end }}
  secret-key: {{ if .Values.global.persistence.secretKey }}{{ .Values.global.persistence.secretKey | b64enc | quote }}{{ else }}{{ include "minio.secretKey" . | b64enc | quote }}{{ end }}
{{- end }}
{{- end }}