{{- if and .Values.global.persistence.mode (eq .Values.global.persistence.mode "minio")}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "minio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
secrets:
  - name: {{ include "common.names.fullname" . }}
{{- end }}
{{- end }}