name: 'Release'
description: 'update contents of the repo for a global or local release'
inputs:
  release:
    description: release type
    required: true

  registry_url:
    description: dockerhub registry url
    required: true

  service_image_name:
    description: the name of the image to be updated
    required: true
        
  tag:
    description: version tag of the image
    required: true

runs:
  using: "composite"

  steps:
    - name: Set dynamic environment variables
      id: var
      shell: bash
      run: |
        case ${{ inputs.service_image_name }} in

          serving-gateway)
            HELM_CHART_NAME=gateway
            SERVICE_NAME=hydro-serving-gateway
            ;;

          serving-manager)
            HELM_CHART_NAME=manager
            SERVICE_NAME=hydro-serving-manager
            ;;

          hydro-root-cause)
            HELM_CHART_NAME=rootcause
            SERVICE_NAME=hydro-root-cause
            ;;

          sonar)
            HELM_CHART_NAME=sonar
            SERVICE_NAME=sonar
            ;;

          hydro-stat)
            HELM_CHART_NAME=stat
            SERVICE_NAME=stat
            ;;

          hydro-serving-ui)
            HELM_CHART_NAME=ui
            SERVICE_NAME=hydro-serving-ui
            ;;  

          hydro-auto-od)
            HELM_CHART_NAME=auto-od
            SERVICE_NAME=hydro-auto-od
            ;;  

          hydro-visualization)
            HELM_CHART_NAME=visualization
            SERVICE_NAME=hydro-visualization
            ;;

          *)
            echo "unknown IMAGE_NAME"
            exit 1
            ;;
        esac
        
        echo ::set-output name=HELM_CHART_NAME::$HELM_CHART_NAME
        echo ::set-output name=SERVICE_NAME::$SERVICE_NAME
        
        
    - name: Update ${{ steps.var.ouputs.HELM_CHART_NAME }}/values.yaml
      run: "cd helm && sed -i \"s/.*full:.*/  full: ${{ inputs.registry_url }}\\/${{ inputs.service_image_name }}:${{ inputs.tag }}/g\" ${{ steps.var.outputs.HELM_CHART_NAME }}/values.yaml"
      shell: bash

    - name: Update dev.yaml
      run: "cd helm && sed -i \"s/.*full:.*${{ inputs.service_image_name }}.*/    full: ${{ inputs.registry_url }}\\/${{ inputs.service_image_name }}:${{ inputs.tag }}/g\" dev.yaml"
      shell: bash
      
      # TODO: linting and stuff

    - name: Update docker-compose service image
      run: "cd docker-compose && sed -i \"s/.*image:.*/    image: ${{ inputs.registry_url }}\\/${{ inputs.service_image_name }}:${{ inputs.tag }}/g\" ${{ steps.var.outputs.SERVICE_NAME }}.service.template"
      shell: bash
      
    - name: Merge compose file
      shell: bash
      run: |
        cd docker-compose
        command="docker-compose"
        for template in $(ls *.template)
        do
          command="$command -f $template"
        done

        command="$command config"
        $command > ../docker-compose.yaml  
