# Default values for sonar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ui:
    ingress:
      enabled: false

  persistence:
    url: ""
    mode: "minio"
    accessKey: "ACCESSKEYEXAMPLE" #accesskeyid for s3 or minio
    secretKey: "SECRETKEYEXAMPLE" #secretkeyid for s3 or minio

  mongodb:
    url: "" #Mongodb address if external mongodb use. Left blank if want use internal mongodb
    rootPassword: "hydr0s3rving" #Mongodb root password
    username: "root" #Mongodb username
    password: "hydr0s3rving" #Mongodb password
    authDatabase: "admin" #Mongodb auth database
    database: "hydro-serving-data-profiler" #Mongodb database name

  postgresql:
    url: "" #Postgresql address if external postgresql use. Left blank if want use internal postgresql
    username: "postgres"  #Postgresql username
    password: "hydr0s3rving" #Postgresql password
    database: "hydro-serving" #Postgresql database name 

  alertmanager:
    url: "" # Prometheus AlertManager address in case you want to use the external installation.
            # If empty, an internal installation will be deployed.
    config:
      global: 
        smtp_smarthost: "localhost:25" # SMTP relay host
        smtp_auth_username: "mailbot" # SMTP relay username 
        smtp_auth_identity: "mailbot" # SMTP relay username identity
        smtp_auth_password: "mailbot" # SMTP relay password
        smtp_from: "no-reply@hydrosphere.io" # Email address of the sender
      route:
        group_by: ["alertname", "modelVersionId"]
        group_wait: "10s"
        group_interval: "10s"
        repeat_interval: "1h"
        receiver: "default"
      receivers:
      - name: "default"
        email_configs: # List of email addresses to send alarms to
        - to: "customer@example.io"

  tolerations: []

persistence:
  bucket: hydrosphere-feature-lake
  # region: us-east-1

alertmanager:
  hydrosphereUrl: "http://example.com"

dbType: postgres
sidecar:
  grpcPort: 8081
  
javaOpts: -Xmx2048m -Xmn2048m -Xss258k -XX:MaxMetaspaceSize=1024m -XX:+AggressiveHeap

replicaCount: 1

image:
  full: hydrosphere/sonar:495830e0910b65420c79e307d3b9df7f1a87917b
  pullPolicy:  IfNotPresent

service:
  type: ClusterIP
  httpPort: 9090
  grpcPort: 9091

resources: 
  limits:
    memory: 4Gi
  requests:
    memory: 512Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
