apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: rootcause-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "rootcause.name" . }}
      release: {{ .Release.Name }}