# Default values for sonar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  full: hydrosphere/hydro-visualization:0927ceaf1c86c03f885f78f88fdfd706be3f38aa
  pullPolicy:  IfNotPresent

persistence:
  bucket: "hydrosphere-visualization-artifacts"
  # region: "us-east-1"
  
global:
  persistence:
    url: ""
    mode: "minio"
    accessKey: "ACCESSKEYEXAMPLE"
    secretKey: "SECRETKEYEXAMPLE"
    region: "us-east-1"

  mongodb:
    url: "" #Mongodb address if external mongodb use
    rootPassword: "hydr0s3rving" #Mongodb root password
    username: "root" #Mongodb username
    password: "hydr0s3rving" #Mongodb password
    authDatabase: "admin" #Mongodb auth database
    database: "hydro-serving-data-profiler" #Mongodb database name

  tolerations: []
  
service:
  type: ClusterIP
  httpPort: 5000
  grpcPort: 5003

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
