FROM hydrosphere/pipelineserving-python3:1.0-SNAPSHOT

RUN apk add --no-cache libstdc++ lapack-dev \
            g++ linux-headers gfortran musl-dev \
            python3-dev && \
        ln -s locale.h /usr/include/xlocale.h && \
        pip install numpy && \
        pip install pandas && \
        pip install scipy && \
        pip install scikit-learn && \
        find /usr/lib/python3.*/ -name 'tests' -exec rm -r '{}' + && \
        rm /usr/include/xlocale.h && \
        rm -r /root/.cache
