{{- if eq .Values.global.alertmanager.url ""}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
data:
  alertmanager.yml: |-
{{ toYaml .Values.global.alertmanager.config | indent 4 }} 
{{- end }}
