{{- if and .Values.serviceAccount.create (eq .Values.global.alertmanager.url "") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertmanager.serviceAccountName" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
