annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2021.5.27
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Bitnami Object Storage based on MinIO(R) is an object storage server,
  compatible with Amazon S3 cloud storage service, mainly used for storing unstructured
  data (such as photos, videos, log files, etc.)
home: https://github.com/bitnami/charts/tree/master/bitnami/minio
icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
keywords:
- minio
- storage
- object-storage
- s3
- cluster
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: minio
sources:
- https://github.com/bitnami/bitnami-docker-minio
- https://min.io
version: 6.7.16
