#Check helm chart, update helm docs

name: "Helm chart Lint and Testing"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Helm:
    runs-on: ubuntu-latest
    name: Check helm charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs helm)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs helm

      # TODO: Run for only serving chart
      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.0.0
      #   if: steps.list-changed.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   run: ct install --chart-dirs helm