#Check helm chart, update helm docs

name: "Helm chart Lint and Testing"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Helm:
    runs-on: ubuntu-latest
    name: Check helm charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs helm)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=helm-changed::$changed"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs helm

      - name: Install frigate and gen docs
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          pip install frigate
          for h in ${{ steps.list-changed.outputs.helm-changed }}
          do 
            frigate gen --no-credits -o markdown $h > $h/README.md
          done

      - name: Push to repo
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Gen readme for ${{ steps.list-changed.outputs.helm-changed }}" -a
          git push
      # TODO: Run for only serving chart
      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.0.0
      #   if: steps.list-changed.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   run: ct install --chart-dirs helm